

// "use client"; 

// import "bootstrap/dist/css/bootstrap.min.css"; // Bootstrap
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import Sidebar from "./Components/Sidebar";
// import TopNav from "./Components/TopNav";
// import { useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   const [isCollapsed, setIsCollapsed] = useState(false);

//   return (
//     <html lang="en">
//       <head>
//         <link
//   rel="stylesheet"
//   href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
// />

//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//        <div className="app-layout">
//   <Sidebar isCollapsed={isCollapsed} />
  
//   <div className={`main-content ${isCollapsed ? "collapsed" : ""}`}>
//     <TopNav setIsCollapsed={setIsCollapsed} isCollapsed={isCollapsed} />
    
//     <div className="content">
//       {children}
//     </div>
//   </div>
// </div>

//       </body>
//     </html>
//   );
// }


import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutClient from "./LayoutClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
